version: 2.1
commands:
  installAWSCLI:
    description: "A command to install the AWS full command line"
    steps:
      - run:
          name: Install AWS Full Command Line (GET)
          command: curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
      - run:
          name: Install AWS Full Command Line (Unzip)
          command: unzip awscli-bundle.zip
      - run:
          name: Install AWS Full Command Line (Install)
          command: binary=$(which python) && sudo $binary ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws && aws --version
jobs:
  test-image:
    docker:
      # - image: cimg/python:3.7.12-node
      - image: circleci/python:3.9.6-node
    steps:
      - checkout
      # - run:
      #     name: Install AWS Full Command Line (GET)
      #     command: curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
      # - run:
      #     name: Install AWS Full Command Line (Unzip)
      #     command: unzip awscli-bundle.zip
      # - run:
      #     name: Install AWS Full Command Line (Install)
      #     command: binary=$(which python) && sudo $binary ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws && aws --version
      - installAWSCLI

workflows:
  version: 2
  pipeline-test:
    jobs:
    - test-image:
        filters:
          branches:
            only:
            - master